FROM python:3.12-slim

WORKDIR /app

COPY requirements-cloudrun.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements-cloudrun.txt

COPY config.py .
COPY http_app.py .

COPY bot ./bot
COPY services ./services

RUN mkdir -p /app/data

COPY data/openai_index.faiss \
    ./data/openai_index.faiss

COPY data/openai_chunks.json \
    ./data/openai_chunks.json

ENV PYTHONUNBUFFERED=1
ENV PORT=8080

CMD ["sh", "-c", "uvicorn http_app:app --host 0.0.0.0 --port ${PORT}"]